/**
 * Public entry point for the generated API client types.
 *
 * `schema.ts` is auto-generated by openapi-typescript from
 * `backend/openapi.json` (run `npm run gen:api`). Do not edit it by hand.
 *
 * This barrel re-exports the raw `paths` / `components` / `operations`
 * interfaces plus flat aliases for every schema, so components can write
 * `Product` instead of `components["schemas"]["ProductResponse"]`.
 */
import type { components, operations, paths } from "./schema";

export type { components, operations, paths };

/** All named schemas defined in the OpenAPI spec. */
export type Schemas = components["schemas"];

// --- Enums -----------------------------------------------------------------
export type UserRole = Schemas["UserRole"];
export type ProductStatus = Schemas["ProductStatus"];
export type OrderStatus = Schemas["OrderStatus"];

// --- Auth ------------------------------------------------------------------
export type RegisterRequest = Schemas["RegisterRequest"];
export type LoginRequest = Schemas["LoginRequest"];
export type UserResponse = Schemas["UserResponse"];

// --- Products --------------------------------------------------------------
export type ProductCreate = Schemas["ProductCreate"];
export type ProductUpdate = Schemas["ProductUpdate"];
export type ProductResponse = Schemas["ProductResponse"];

// --- Cart ------------------------------------------------------------------
export type CartItemAdd = Schemas["CartItemAdd"];
export type CartItemUpdate = Schemas["CartItemUpdate"];
export type CartItemResponse = Schemas["CartItemResponse"];
export type CartResponse = Schemas["CartResponse"];

// --- Orders / checkout -----------------------------------------------------
export type ShippingAddress = Schemas["ShippingAddress"];
export type CheckoutRequest = Schemas["CheckoutRequest"];
export type CheckoutResponse = Schemas["CheckoutResponse"];
export type OrderItemResponse = Schemas["OrderItemResponse"];
export type OrderResponse = Schemas["OrderResponse"];
export type OrderStatusUpdate = Schemas["OrderStatusUpdate"];
export type TrackingStage = Schemas["TrackingStage"];
export type TrackingResponse = Schemas["TrackingResponse"];

// --- Reviews ---------------------------------------------------------------
export type ReviewCreate = Schemas["ReviewCreate"];
export type ReviewUpdate = Schemas["ReviewUpdate"];
export type ReviewResponse = Schemas["ReviewResponse"];

// --- Merchant --------------------------------------------------------------
export type MerchantDashboard = Schemas["MerchantDashboard"];
export type RevenueWindows = Schemas["RevenueWindows"];
export type RevenueSummary = Schemas["RevenueSummary"];
export type TopProduct = Schemas["TopProduct"];
export type LowStockProduct = Schemas["LowStockProduct"];

// --- Admin -----------------------------------------------------------------
export type AdminUserResponse = Schemas["AdminUserResponse"];
export type AdminUserUpdate = Schemas["AdminUserUpdate"];
export type PlatformStats = Schemas["PlatformStats"];

// --- Webhooks --------------------------------------------------------------
export type WebhookAck = Schemas["WebhookAck"];

// --- Errors & pagination ---------------------------------------------------
export type ProblemDetail = Schemas["ProblemDetail"];
export type HTTPValidationError = Schemas["HTTPValidationError"];
export type ValidationError = Schemas["ValidationError"];

export type PageProductResponse = Schemas["Page_ProductResponse_"];
export type PageOrderResponse = Schemas["Page_OrderResponse_"];
export type PageReviewResponse = Schemas["Page_ReviewResponse_"];
export type PageAdminUserResponse = Schemas["Page_AdminUserResponse_"];
